feat(graph) full path emphasis.
apache/echarts-doc pull request #276
Opened 2022-08-01 07:59 UTC by ElayGelbart

* apache/echarts/pull/17451

2022-08-25 09:31 UTC, Ovilia commented on en/api/events.md
Please rebase the commit to remove the changes in other PRs.

2023-01-04 14:05 UTC, plainheart requested changes

2023-01-04 14:05 UTC, plainheart commented on en/api/events.md
> +Event emitted after [series-graph](option.html#series-graph) is roamed.
There seem to be some redundant commits, please rebase to the latest master branch.

2023-03-09 10:20 UTC, plainheart requested changes

2023-03-09 10:20 UTC, plainheart commented on en/option/partial/emphasis-common.md
> ++ `'trajectory'` Focus on all the elements connected to the node or edge in the graph.
As per #17451, only the `sankey` series support this feature.

2023-03-13 14:56 UTC, merged