chore: changelog for `5.4.1`
apache/echarts-doc pull request #318
Opened 2022-11-30 15:07 UTC by susiwen8

2022-11-30 15:14 UTC, plainheart requested changes

2022-11-30 15:14 UTC, plainheart commented on en/changelog.md
> +## 5.4.1
Missing `v` before `5.4.1`

2022-11-30 15:14 UTC, plainheart commented on en/changelog.md
> ++ feat(i18n): add Hungarian(hu_HU) translation [#17978](https://github.com/apache/echarts/issues/17978) ([ifjkovacsik](https://github.com/ifjkovacsik))
The format should be like `[type] [scope]: message`.

2022-11-30 15:35 UTC, plainheart commented on en/changelog.md
> ++ [Fix] [lines)]: add missing `function` callback into `lineStyle.color` for lines series. [#17780](https://github.com/apache/echarts/issues/17780) ([plainheart](https://github.com/plainheart))
The scope of this change should be `type` rather than `lines` and please put this item below.

2022-11-30 15:35 UTC, plainheart commented on en/changelog.md
> ++ [Fix] [i18n]: language code for Ukrainian is UK, not UA (follow-up) [#17812](https://github.com/apache/echarts/issues/17812) ([striezel](https://github.com/striezel))
The message of this item needs to be updated. https://github.com/apache/echarts/pull/17812

2022-11-30 15:35 UTC, plainheart commented on en/changelog.md
> ++ [Fix] [type]: add overflow property to AxisLabelBaseOption interface. close #17363 [#17808](https://github.com/apache/echarts/issues/17808) ([breizh24](https://github.com/breizh24))
It's good to wrap the keyword `overflow` & `AxisLabelBaseOption` with \`

2022-11-30 15:35 UTC, plainheart commented on en/changelog.md
> ++ [Fix] [universalTransition]: incorrect dataGroupId for old data items in universalTransition [#17559](https://github.com/apache/echarts/issues/17559) ([tyn1998](https://github.com/tyn1998))
It's better to set the scope to `animation`

2022-11-30 16:05 UTC, plainheart commented on en/changelog.md
> ++ [Feature] [svg] Support gradients and patterns for background color in SVG renderer [#959](https://github.com/ecomfe/zrender/issues/959) ([plainheart](https://github.com/plainheart)
Missing `)` in the end

2022-11-30 16:05 UTC, plainheart commented on en/changelog.md
> ++ [Fix] [type] EChartsInitOpts type error about height and width. close #17667 [#17727](https://github.com/apache/echarts/issues/17727) ([MainHou](https://github.com/MainHou))
Wrap the `EChartsInitOpts` and add **'Fix'** before it

2022-11-30 16:16 UTC, plainheart commented on en/changelog.md
> ++ [Feature] [candlestick] Provide borderColorDoji option for custom doji color. [#17717](https://github.com/apache/echarts/issues/17717) ([Ovilia](https://github.com/Ovilia))
Wrap `borderColorDoji`

2022-12-01 01:33 UTC, susiwen8 commented on en/changelog.md
> ++ [Fix] [type] Add missing `function` callback into `lineStyle.color` for lines series. [#17780](https://github.com/apache/echarts/issues/17780) ([plainheart](https://github.com/plainheart))
Sure

2022-12-01 02:00 UTC, Ovilia approved these changes
LGTM

2022-12-01 02:17 UTC, plainheart approved these changes

2022-12-01 02:28 UTC, merged